name : step 3 Install Dependencies
on: 
 push:
   branches: 
    - main
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: show files
     run : ls -lrtha
   
   - name : Install dependincies
     run : npm install
   - name : Running App
     run : node app.js
   
