name : step 3 Install Dependencies
on: 
 push:
   branches: 
    - main
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: show files
     run : ls -lrtha
   
   - name : Install dependincies
     run : npm install
   - name : Running App
     run : node app.js
   - name: Deploy to EC2
     uses: appleboy/ssh-action@v0.1.6
     with :
      host : ${{secrets.EC2_HOST}}
      username: ${{secrets.EC2_USER}}
      key : ${{secrets.EC2_SSH_KEY}}
      script :  |
        cd /home/ubuntu/app || git clone https://github.com/DevOpsCloudZone/Projects.git  app
        cd app
        git pull origin main
        npm install
        pm2 restart app || pm2 start app.js --name app
      
   
